// Displays the number of instances the function app scaled to over a period of time. Supply a start and end time for the query range and update the cluster uri with the appropriate values from your terraform deployment.

let startTime = todatetime(<QUERY_START_TIME>);
let endTime =  todatetime(<QUERY_END_TIME>);
cluster("https://ade.applicationinsights.io/subscriptions/<SUBSCRIPTION_ID>/resourcegroups/<BASE_NAME>-rg/providers/microsoft.insights/components/<BASE_NAME><REGION>").database("<BASE_NAME><REGION>").requests
| where timestamp between (startTime .. endTime)
| summarize InstanceCount = dcount(cloud_RoleInstance) by bin(timestamp, 1s);